#!/bin/bash

export CLASSPATH=./jar/Icarus.jar
export CLASSPATH=${CLASSPATH}\;./lib/optaplanner-core-6.4.0.Final.jar
export CLASSPATH=${CLASSPATH}\;./lib/optaplanner-benchmark-6.4.0.Final.jar
export CLASSPATH=${CLASSPATH}\;./lib/optaplanner-persistence-common-6.4.0.Final.jar
export CLASSPATH=${CLASSPATH}\;./lib/java-json.jar
export CLASSPATH=${CLASSPATH}\;./lib/javassist-3.18.1-GA.jar
export CLASSPATH=${CLASSPATH}\;./lib/xstream-1.4.7.jar
export CLASSPATH=${CLASSPATH}\;./lib/kie-api-6.4.0.Final.jar
export CLASSPATH=${CLASSPATH}\;./lib/slf4j-api-1.7.2.jar
export CLASSPATH=${CLASSPATH}\;./lib/slf4j-simple-1.6.1.jar
export CLASSPATH=${CLASSPATH}\;./lib/xmlpull-1.1.3.1.jar
export CLASSPATH=${CLASSPATH}\;./lib/google-collections-1.0.jar
export CLASSPATH=${CLASSPATH}\;./lib/reflections-0.9.10.jar
export CLASSPATH=${CLASSPATH}\;./lib/commons-io-2.4.jar
export CLASSPATH=${CLASSPATH}\;./lib/commons-lang3-3.1.jar
export CLASSPATH=${CLASSPATH}\;./lib/commons-math3-3.4.1.jar
export CLASSPATH=${CLASSPATH}\;./lib/xpp3_min-1.1.4c.jar
export CLASSPATH=${CLASSPATH}\;./lib/logback-core-1.0.9.jar
export CLASSPATH=${CLASSPATH}\;./lib/jackson-core-2.8.6.jar
export CLASSPATH=${CLASSPATH}\;./lib/jackson-annotations-2.8.6.jar
export CLASSPATH=${CLASSPATH}\;./lib/jackson-databind-2.8.6.jar
export CLASSPATH=${CLASSPATH}\;./lib/jfreechart-1.0.19.jar
export CLASSPATH=${CLASSPATH}\;./lib/jcommon-1.0.23.jar
export CLASSPATH=${CLASSPATH}\;./lib/freemarker-2.3.19.jar
export CLASSPATH=${CLASSPATH}\;./resources

#TODO fix this to use an env variable to determine whether to debug or not
#TODO - Run this off JAVA_HOME?
#/c/Program\ Files/Java/jdk1.8.0_121/bin/java -server -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=8000 icarus.application.CellTowerApp $*
/c/Program\ Files/Java/jdk1.8.0_121/bin/java -server icarus.application.CellTowerApp $*